### ISSUE TITLE
Logs wont work anymore

### ISSUE THREAD

**Issue by lucas19961** [gempir/justlog#197]
JustLogs stopped working,

Not just my instace also the logs.ivr.fi instance. The Logs load for a second an the the page ist black. 

Here ist the Error from the Console 

`index-d5f32233.js:40 TypeError: Cannot read properties of undefined (reading 'name')
    at Ntt (index-d5f32233.js:364:11931)
    at Fq (index-d5f32233.js:364:14282)
    at Nrt (index-d5f32233.js:406:433)
    at rA (index-d5f32233.js:38:19540)
    at cw (index-d5f32233.js:40:3139)
    at wF (index-d5f32233.js:40:44830)
    at EF (index-d5f32233.js:40:39787)
    at pV (index-d5f32233.js:40:39715)
    at Jg (index-d5f32233.js:40:39568)
    at Sw (index-d5f32233.js:40:35933)`

`index-d5f32233.js:364 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at Ntt (index-d5f32233.js:364:11931)
    at Fq (index-d5f32233.js:364:14282)
    at Nrt (index-d5f32233.js:406:433)
    at rA (index-d5f32233.js:38:19540)
    at cw (index-d5f32233.js:40:3139)
    at wF (index-d5f32233.js:40:44830)
    at EF (index-d5f32233.js:40:39787)
    at pV (index-d5f32233.js:40:39715)
    at Jg (index-d5f32233.js:40:39568)
    at Sw (index-d5f32233.js:40:35933)`

**Comment by lucas19961** [comment]
![zsbL1QP](https://github.com/gempir/justlog/assets/17136546/f2b271dd-906f-4e63-a236-6d9d39ae6109)
![-G4W4L4](https://github.com/gempir/justlog/assets/17136546/68ce922e-5c54-48a8-80f6-b56e1b7637ce)

I think its a bug with the preview of 7tv emotes. 
![image](https://github.com/gempir/justlog/assets/17136546/44aa2564-9d08-4322-b142-ad90c20811b9)
Logs no longer load in channels where a bugged emote was used (Huge 7tv Emote).

**Comment by gempir** [comment]
I merged your PR, but idk the release process of logs.ivr.fi anymore. Its tied to rustlog and that one uses my frontend, so it will need the update too.
